
// subirProductos.js - PARA FIREBASE v8
const firebase = require('firebase/app');
require('firebase/firestore');

// Tu configuración de Firebase
const firebaseConfig = {
  apiKey: "AIzaSyBmecDvGI7jtqDEO2ajTiu7Jsy6J83Kb3o",
  authDomain: "estrella-gc-tienda.firebaseapp.com",
  projectId: "estrella-gc-tienda",
  storageBucket: "estrella-gc-tienda.firebasestorage.app",
  messagingSenderId: "36924682007",
  appId: "1:36924682007:web:65e5095621aa3777339152",
  measurementId: "G-LNKF6N4F77"
};

// Inicializar Firebase
firebase.initializeApp(firebaseConfig);
const db = firebase.firestore();

// Tu array de productos (mantén igual)
const productos = [
 
  {
    "nombre": "PINOL 1L ORIGINAL",
    "precio": 32.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "LIMPIADOR MULTI USOS",
    "stock": 5.0,
    "destacado": false,
    "codigoBarras": "7501025462017",
    "proveedor": "ZORRO",
    "marca": "PINOL",
    "pesoVolumen": 1.0,
    "unidadMedida": "ML",
    "precioCompra": 27.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-12-12"
  },
  {
    "nombre": "DONUTS 75g HERSHEYS",
    "precio": 15.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "HERSHEYS 75g",
    "stock": 1.0,
    "destacado": false,
    "codigoBarras": "7500810047514",
    "proveedor": "BIMBO",
    "marca": "BIMBO",
    "pesoVolumen": 75.0,
    "unidadMedida": "PZS",
    "precioCompra": 11.53,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-04-27"
  },
  {
    "nombre": "MARLBORO 100 20c",
    "precio": 105.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CAJA DE CIGARROS",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "75021597",
    "proveedor": "MARLOBORO",
    "marca": "MARLBORO",
    "pesoVolumen": 100.0,
    "unidadMedida": "PZS",
    "precioCompra": 94.24,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-12-12"
  },
  {
    "nombre": "MARLBORO 100 20c",
    "precio": 8.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CAJA DE CIGARROS",
    "stock": 6.0,
    "destacado": false,
    "codigoBarras": "75021597",
    "proveedor": "MARLOBORO",
    "marca": "MARLBORO",
    "pesoVolumen": 100.0,
    "unidadMedida": "PZS",
    "precioCompra": 4.71,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-12-12"
  },
  {
    "nombre": "MALBORO BLOSSOM",
    "precio": 8.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "INDIVIDUAL",
    "stock": 5.0,
    "destacado": false,
    "codigoBarras": "75085384",
    "proveedor": "MARLBORO",
    "marca": "MARLBORO",
    "pesoVolumen": 1.0,
    "unidadMedida": "PZS",
    "precioCompra": 3.20,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-12-12"
  },
  {
    "nombre": "GRIEGO 120g FRESA",
    "precio": 10.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "FRESA",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "7506443109711",
    "proveedor": "DANONE",
    "marca": "DANONE",
    "pesoVolumen": 120.0,
    "unidadMedida": "Pieza",
    "precioCompra": 8.10,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-04-30"
  },
  {
    "nombre": "SKWINKLES 45g",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CHUNKS",
    "stock": 7.0,
    "destacado": false,
    "codigoBarras": "7502271914619",
    "proveedor": "ZORRO",
    "marca": "SKWINKLES",
    "pesoVolumen": 45.0,
    "unidadMedida": "Pieza",
    "precioCompra": 15.53,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-01-17"
  },
  {
    "nombre": "HERSHEY S 20g",
    "precio": 10.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CHOCLATE Y ALMENDRAS",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "7501024513604",
    "proveedor": "COCA COLA",
    "marca": "HERSHEY",
    "pesoVolumen": 20.0,
    "unidadMedida": "PZS",
    "precioCompra": 6.60,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-02-02"
  },
  {
    "nombre": "HEAD & SHOULDERS 180ml",
    "precio": 40.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "LIMPIEZA RENOVADORA",
    "stock": 1.0,
    "destacado": false,
    "codigoBarras": "7500435019958",
    "proveedor": "COCA COLA",
    "marca": "HEAD & SHOULDERS",
    "pesoVolumen": 180.0,
    "unidadMedida": "ml",
    "precioCompra": 27.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2029-01-11"
  },
  {
    "nombre": "VIVE 100 600ml",
    "precio": 22.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "BLUE ENERGY",
    "stock": 1.0,
    "destacado": false,
    "codigoBarras": "7506192510295",
    "proveedor": "BEES",
    "marca": "VIVE",
    "pesoVolumen": 600.0,
    "unidadMedida": "ML",
    "precioCompra": 14.50,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-04-13"
  },
  {
    "nombre": "trident fresa",
    "precio": 4.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "TRIDENT 5´S FRESHMINT",
    "stock": 75.0,
    "destacado": false,
    "codigoBarras": "75045654",
    "proveedor": "MONDELEZ",
    "marca": "ADAMS",
    "pesoVolumen": 52.0,
    "unidadMedida": "Pieza",
    "precioCompra": 2.17,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-07-15"
  },
  {
    "nombre": "sol mangoyada",
    "precio": 29.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CERVEZA SOL",
    "stock": 23.0,
    "destacado": false,
    "codigoBarras": "7503032272375",
    "proveedor": "TECATE",
    "marca": "SOL",
    "pesoVolumen": 473.0,
    "unidadMedida": "PZS",
    "precioCompra": 23.45,
    "puntoReorden": 1,
    "fechaVencimiento": "2054-12-20"
  },
  {
    "nombre": "bong de uva 250 ml",
    "precio": 12.50,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "INDIVIDUAL",
    "stock": 4.0,
    "destacado": false,
    "codigoBarras": "75001834",
    "proveedor": "MARLBORO",
    "marca": "MARLBORO",
    "pesoVolumen": 250.0,
    "unidadMedida": "PZS",
    "precioCompra": 8.50,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-26"
  },
  {
    "nombre": "boing",
    "precio": 12.50,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "INDIVIDUAL",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "75001759",
    "proveedor": "MARLBORO",
    "marca": "MARLBORO",
    "pesoVolumen": 250.0,
    "unidadMedida": "PZS",
    "precioCompra": 8.50,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-26"
  },
  {
    "nombre": "boing guayaba",
    "precio": 12.50,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "pieza",
    "stock": 5.0,
    "destacado": false,
    "codigoBarras": "75001773",
    "proveedor": "BOING",
    "marca": "boing",
    "pesoVolumen": 250.0,
    "unidadMedida": "PZS",
    "precioCompra": 8.50,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-26"
  },
  {
    "nombre": "boing",
    "precio": 12.50,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "pieza",
    "stock": 4.0,
    "destacado": false,
    "codigoBarras": "75001797",
    "proveedor": "BOING",
    "marca": "boing",
    "pesoVolumen": 250.0,
    "unidadMedida": "PZS",
    "precioCompra": 8.50,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-26"
  },
  {
    "nombre": "CHOCO 135g KRISPIS",
    "precio": 27.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CEREAL",
    "stock": 6.0,
    "destacado": false,
    "codigoBarras": "7501008019283",
    "proveedor": "COCA COLA",
    "marca": "KELLOGGS",
    "pesoVolumen": 135.0,
    "unidadMedida": "Pieza",
    "precioCompra": 23.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-09-04"
  },
  {
    "nombre": "TOSTACHOS 75g",
    "precio": 18.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "QUESO JALAPEÑO",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7500810037294",
    "proveedor": "BARCEL",
    "marca": "TOSTACHOS",
    "pesoVolumen": 75.0,
    "unidadMedida": "Pieza",
    "precioCompra": 14.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-08-10"
  },
  {
    "nombre": "jalapeños 220g enteros",
    "precio": 17.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "Producto JALAPEÑOS PICADOS  de alta calidad",
    "stock": 7.0,
    "destacado": false,
    "codigoBarras": "7501017005000",
    "proveedor": "LA COSTEÑA",
    "marca": "COSTEÑA",
    "pesoVolumen": 220.0,
    "unidadMedida": "Pieza",
    "precioCompra": 12.50,
    "puntoReorden": 1,
    "fechaVencimiento": "2029-09-09"
  },
  {
    "nombre": "golos bokados",
    "precio": 10.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "BOKADOS 85GR MIX CON GOLOS",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "730399006122",
    "proveedor": "BOKADOS",
    "marca": "BOKADOS",
    "pesoVolumen": 45.0,
    "unidadMedida": "PZS",
    "precioCompra": 7.81,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-05-11"
  },
  {
    "nombre": "PRISPAS 27g PICOSITAS",
    "precio": 10.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "PICOSITAS",
    "stock": 12.0,
    "destacado": false,
    "codigoBarras": "730399018170",
    "proveedor": "BOKADOS",
    "marca": "PRISPAS",
    "pesoVolumen": 27.0,
    "unidadMedida": "Pieza",
    "precioCompra": 8.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-06-18"
  },
  {
    "nombre": "TRIDENT MENTA FRESCA",
    "precio": 4.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "TRIDENT 5´S FRESHMINT",
    "stock": 20.0,
    "destacado": false,
    "codigoBarras": "75045494",
    "proveedor": "MONDELEZ",
    "marca": "ADAMS",
    "pesoVolumen": 5.0,
    "unidadMedida": "Pieza",
    "precioCompra": 12.16,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-07-12"
  },
  {
    "nombre": "CHICLETS",
    "precio": 2.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "TRIDENT 5´S FRESHMINT",
    "stock": 71.0,
    "destacado": false,
    "codigoBarras": "7622210535207",
    "proveedor": "MONDELEZ",
    "marca": "ADAMS",
    "pesoVolumen": 210.0,
    "unidadMedida": "Pieza",
    "precioCompra": 0.64,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-08-27"
  },
  {
    "nombre": "BUBU LUBU 35g DARK",
    "precio": 14.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MALVAVISCO",
    "stock": 9.0,
    "destacado": false,
    "codigoBarras": "757528021757",
    "proveedor": "MONDALEZ",
    "marca": "BUBU LUBU",
    "pesoVolumen": 35.0,
    "unidadMedida": "PZS",
    "precioCompra": 8.96,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-09-05"
  },
  {
    "nombre": "TOSTITOS 62g FLAMING HOT",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "FLAMING HOT",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "7501011126879",
    "proveedor": "SABRITAS",
    "marca": "TOSTITOS",
    "pesoVolumen": 62.0,
    "unidadMedida": "pzs",
    "precioCompra": 15.85,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-12"
  },
  {
    "nombre": "fibra duramax paquete 3",
    "precio": 25.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "Producto fibra dura de alta calidad",
    "stock": 7.0,
    "destacado": false,
    "codigoBarras": "1136",
    "proveedor": "jarceria",
    "marca": "libre",
    "pesoVolumen": 8.0,
    "unidadMedida": "Pieza",
    "precioCompra": 17.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2090-02-02"
  },
  {
    "nombre": "BIG MIX 185g QUESO",
    "precio": 42.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "QUESO",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "757528039288",
    "proveedor": "BARCEL",
    "marca": "BARCEL",
    "pesoVolumen": 185.0,
    "unidadMedida": "PZS",
    "precioCompra": 31.11,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-13"
  },
  {
    "nombre": "MAMUT 44g",
    "precio": 10.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "GALLETA SANDWICH",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "7501000651375",
    "proveedor": "GAMESA",
    "marca": "MAMUT",
    "pesoVolumen": 44.0,
    "unidadMedida": "PZS",
    "precioCompra": 8.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-09-06"
  },
  {
    "nombre": "JICAMA",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "FRUTA",
    "stock": 0.515,
    "destacado": false,
    "codigoBarras": "6161",
    "proveedor": "GENERICO",
    "marca": "GENERICO",
    "pesoVolumen": 1.52,
    "unidadMedida": "Pieza",
    "precioCompra": 15.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-04-04"
  },
  {
    "nombre": "MANGO FRUTA",
    "precio": 30.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MANGO",
    "stock": 2.667,
    "destacado": false,
    "codigoBarras": "3939",
    "proveedor": "GENERICO",
    "marca": "GENERICO",
    "pesoVolumen": 1.0,
    "unidadMedida": "KG",
    "precioCompra": 20.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-04-30"
  },
  {
    "nombre": "CACAHUATE FR",
    "precio": 120.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CACAHUATE",
    "stock": 0.5,
    "destacado": false,
    "codigoBarras": "7979",
    "proveedor": "GENERICO",
    "marca": "GENERICO",
    "pesoVolumen": 1.0,
    "unidadMedida": "KG",
    "precioCompra": 100.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-04-10"
  },
  {
    "nombre": "MARUCHAN 64g",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "LIME CHILI FLAVOR WITH SHRIMP",
    "stock": 7.0,
    "destacado": false,
    "codigoBarras": "041789001154",
    "proveedor": "ZORRO",
    "marca": "MARUCHAN",
    "pesoVolumen": 64.0,
    "unidadMedida": "PZS",
    "precioCompra": 13.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-12-11"
  },
  {
    "nombre": "MARUCHAN 64g",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CHILI PIQUIN Y SHRIMP",
    "stock": 12.0,
    "destacado": false,
    "codigoBarras": "041789001284",
    "proveedor": "ZORRO",
    "marca": "MARUCHAN",
    "pesoVolumen": 64.0,
    "unidadMedida": "PZS",
    "precioCompra": 13.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-01-21"
  },
  {
    "nombre": "ENSUEÑO 850ml AZUL",
    "precio": 30.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "FRESCURA AZUL",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7501025401610",
    "proveedor": "ZORRO",
    "marca": "ENSUEÑO",
    "pesoVolumen": 850.0,
    "unidadMedida": "ML",
    "precioCompra": 22.68,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-07-07"
  },
  {
    "nombre": "ENSUEÑO 850ml PEPINO BAMBU",
    "precio": 30.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "PEPINO MAS BAMBU",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7501025414450",
    "proveedor": "ZORRO",
    "marca": "ENSUEÑO",
    "pesoVolumen": 850.0,
    "unidadMedida": "ML",
    "precioCompra": 22.68,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-03-03"
  },
  {
    "nombre": "ENSUEÑO 850ml LAVANDA",
    "precio": 30.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "LAVANDA Y MORAS",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "7501025443825",
    "proveedor": "ZORRO",
    "marca": "ENSUEÑO",
    "pesoVolumen": 850.0,
    "unidadMedida": "ML",
    "precioCompra": 22.68,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-03-30"
  },
  {
    "nombre": "BAYGON 380ml CASA Y JARDIN",
    "precio": 72.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MOSQUITOS Y MOSCAS",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7501032900618",
    "proveedor": "ZORRO",
    "marca": "BAYGON",
    "pesoVolumen": 380.0,
    "unidadMedida": "ml",
    "precioCompra": 60.49,
    "puntoReorden": 1,
    "fechaVencimiento": "2028-02-06"
  },
  {
    "nombre": "CARLOS V 20g",
    "precio": 13.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "SEMIAMARGO",
    "stock": 12.0,
    "destacado": false,
    "codigoBarras": "7501059299252",
    "proveedor": "ZORRO",
    "marca": "CARLOS V",
    "pesoVolumen": 20.0,
    "unidadMedida": "PZS",
    "precioCompra": 7.71,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-03-31"
  },
  {
    "nombre": "CODO 200g 2",
    "precio": 10.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "PASTA DE SEMOLA DE TRIGO DURUM",
    "stock": 20.0,
    "destacado": false,
    "codigoBarras": "7501018310523",
    "proveedor": "ZORRO",
    "marca": "MODERNA",
    "pesoVolumen": 200.0,
    "unidadMedida": "Pieza",
    "precioCompra": 7.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2028-03-03"
  },
  {
    "nombre": "REXAL 100g POLVO PARA HORNEAR",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "POLVO PARA HORNEAR",
    "stock": 6.0,
    "destacado": false,
    "codigoBarras": "013602000200",
    "proveedor": "ZORRO",
    "marca": "REXAL",
    "pesoVolumen": 100.0,
    "unidadMedida": "Pieza",
    "precioCompra": 13.02,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-08-08"
  },
  {
    "nombre": "OMEPRAZOL 20mg",
    "precio": 6.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "omeprazol 20g",
    "stock": 28.0,
    "destacado": false,
    "codigoBarras": "7501573902584",
    "proveedor": "ZORRO",
    "marca": "SAROX",
    "pesoVolumen": 20.0,
    "unidadMedida": "pzs",
    "precioCompra": 1.46,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-10-10"
  },
  {
    "nombre": "IBUPROFENO 400g",
    "precio": 8.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "IBUPROFENO 400G",
    "stock": 16.0,
    "destacado": false,
    "codigoBarras": "7503008344785",
    "proveedor": "ZORRO",
    "marca": "GELUBRIN",
    "pesoVolumen": 400.0,
    "unidadMedida": "PZS",
    "precioCompra": 2.24,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-08-08"
  },
  {
    "nombre": "DAN MIX 110g OREO",
    "precio": 24.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "OREO",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "7506443109377",
    "proveedor": "DANONE",
    "marca": "DANONE",
    "pesoVolumen": 110.0,
    "unidadMedida": "PZS",
    "precioCompra": 18.90,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-05-07"
  },
  {
    "nombre": "MIX QUESO 230g",
    "precio": 55.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MEZCLA DE BOTANAS",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "730399033340",
    "proveedor": "BOKADOS",
    "marca": "BOKADOS",
    "pesoVolumen": 230.0,
    "unidadMedida": "PZS",
    "precioCompra": 32.82,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-06-17"
  },
  {
    "nombre": "PANDITAS 20g",
    "precio": 6.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CHOCO COLORES",
    "stock": 17.0,
    "destacado": false,
    "codigoBarras": "7622202345500",
    "proveedor": "MONDELEZ",
    "marca": "RICOLINO",
    "pesoVolumen": 20.0,
    "unidadMedida": "Pieza",
    "precioCompra": 4.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-09-13"
  },
  {
    "nombre": "uva fr",
    "precio": 110.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "Producto uva fr de alta calidad",
    "stock": 1000.0,
    "destacado": false,
    "codigoBarras": "1933",
    "proveedor": "papa",
    "marca": "libre",
    "pesoVolumen": 1.0,
    "unidadMedida": "Pieza",
    "precioCompra": 110.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2090-10-03"
  },
  {
    "nombre": "fresa fr caja",
    "precio": 70.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "Producto fresa fr de alta calidad",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "2933",
    "proveedor": "papa",
    "marca": "libre",
    "pesoVolumen": 2.0,
    "unidadMedida": "Pz",
    "precioCompra": 65.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2090-10-20"
  },
  {
    "nombre": "LUCAS GUSANO 3g",
    "precio": 12.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "chamoy",
    "stock": 14.0,
    "destacado": false,
    "codigoBarras": "725181035015",
    "proveedor": "COCA COLA",
    "marca": "LUCAS",
    "pesoVolumen": 3.0,
    "unidadMedida": "PZS",
    "precioCompra": 7.40,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-03-06"
  },
  {
    "nombre": "GRAYON 28g MANGO",
    "precio": 12.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MANGO",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "719886120251",
    "proveedor": "COCA COLA",
    "marca": "GRAYON",
    "pesoVolumen": 28.0,
    "unidadMedida": "PZS",
    "precioCompra": 7.60,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-11-11"
  },
  {
    "nombre": "GRAYON 28g MANZANA",
    "precio": 12.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MANZANA VERDE",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "719886120312",
    "proveedor": "COCA COLA",
    "marca": "GRAYON",
    "pesoVolumen": 28.0,
    "unidadMedida": "PZS",
    "precioCompra": 7.60,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-11-11"
  },
  {
    "nombre": "GRAYON 28g UVA",
    "precio": 12.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "UVA",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "719886120299",
    "proveedor": "COCA COLA",
    "marca": "GRAYON",
    "pesoVolumen": 28.0,
    "unidadMedida": "PZS",
    "precioCompra": 7.60,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-11-11"
  },
  {
    "nombre": "LUCAS 38g PANZON",
    "precio": 12.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CARAMELO",
    "stock": 12.0,
    "destacado": false,
    "codigoBarras": "7502226815145",
    "proveedor": "COCA COLA",
    "marca": "LUCAS",
    "pesoVolumen": 38.0,
    "unidadMedida": "PZS",
    "precioCompra": 7.60,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-03-11"
  },
  {
    "nombre": "RUFFLES 120g",
    "precio": 38.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "120g",
    "stock": 8.0,
    "destacado": false,
    "codigoBarras": "7501011167674",
    "proveedor": "SABRITAS",
    "marca": "RUFLES",
    "pesoVolumen": 120.0,
    "unidadMedida": "Pieza",
    "precioCompra": 31.11,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-06-07"
  },
  {
    "nombre": "INPIREKA 49g",
    "precio": 25.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CREAR Y COMER",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "8501058138865",
    "proveedor": "SABRITAS",
    "marca": "INSPIREKA",
    "pesoVolumen": 49.0,
    "unidadMedida": "Pieza",
    "precioCompra": 19.62,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-01-21"
  },
  {
    "nombre": "KONSTRU Y 49g",
    "precio": 25.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "DULCE Y JUGUETE",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "7501011138865",
    "proveedor": "SABRITAS",
    "marca": "INSPIREKA",
    "pesoVolumen": 49.0,
    "unidadMedida": "Pieza",
    "precioCompra": 19.62,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-01-21"
  },
  {
    "nombre": "MOLDEABLE 45g",
    "precio": 25.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "DULCE Y JUGUETE",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "7501011147942",
    "proveedor": "SABRITAS",
    "marca": "INSPIREKA",
    "pesoVolumen": 45.0,
    "unidadMedida": "Pieza",
    "precioCompra": 19.62,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-09-15"
  },
  {
    "nombre": "PINTA FRUT 20.4g",
    "precio": 25.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "PLUMA RELLENA DE CARAMELO",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "7501011159969",
    "proveedor": "SABRITAS",
    "marca": "INSPIREKA",
    "pesoVolumen": 20.4,
    "unidadMedida": "Pieza",
    "precioCompra": 19.62,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-01-26"
  },
  {
    "nombre": "SOL 100g SALSA NEGRA",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "SALSA NEGRA",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "7503022458901",
    "proveedor": "LA BOTANITA",
    "marca": "SOL",
    "pesoVolumen": 100.0,
    "unidadMedida": "PZS",
    "precioCompra": 15.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-23"
  },
  {
    "nombre": "SOLCHESITOS 100g",
    "precio": 14.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "EXTREMOS",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "7503022458529",
    "proveedor": "LA BOTANITA",
    "marca": "SOL",
    "pesoVolumen": 100.0,
    "unidadMedida": "Pieza",
    "precioCompra": 10.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-02"
  },
  {
    "nombre": "SOLCHESITO",
    "precio": 14.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "QUESO",
    "stock": 0.0,
    "destacado": false,
    "codigoBarras": "7503022458352",
    "proveedor": "LA BOTANITA",
    "marca": "SOL",
    "pesoVolumen": 100.0,
    "unidadMedida": "Pieza",
    "precioCompra": 10.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-07-10"
  },
  {
    "nombre": "MAR 100g CHURRO CHILE",
    "precio": 14.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CHURRO CHILE",
    "stock": 6.0,
    "destacado": false,
    "codigoBarras": "7503027062127",
    "proveedor": "LA BOTANITA",
    "marca": "MAR",
    "pesoVolumen": 100.0,
    "unidadMedida": "L",
    "precioCompra": 10.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-08-30"
  },
  {
    "nombre": "OYUKI 50g",
    "precio": 12.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "FRITURA DE HARINA DE MAIZ",
    "stock": 5.0,
    "destacado": false,
    "codigoBarras": "7502251196479",
    "proveedor": "LA BOTANITA",
    "marca": "OYUKI",
    "pesoVolumen": 50.0,
    "unidadMedida": "Pieza",
    "precioCompra": 8.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-05-28"
  },
  {
    "nombre": "bubbaloo",
    "precio": 2.50,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "bubbaloo",
    "stock": 44.0,
    "destacado": false,
    "codigoBarras": "75073244",
    "proveedor": "mondales",
    "marca": "INSPIREKAmondales",
    "pesoVolumen": 239.7,
    "unidadMedida": "Pieza",
    "precioCompra": 0.94,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-04-08"
  },
  {
    "nombre": "clorets plus  13g",
    "precio": 15.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "cartera chicles",
    "stock": 10.0,
    "destacado": false,
    "codigoBarras": "7622210571205",
    "proveedor": "mondales",
    "marca": "clores",
    "pesoVolumen": 13.0,
    "unidadMedida": "L",
    "precioCompra": 8.70,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-10-12"
  },
  {
    "nombre": "boing guayaba 354ml",
    "precio": 19.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "boing",
    "stock": 4.0,
    "destacado": false,
    "codigoBarras": "7501039400081",
    "proveedor": "BOING",
    "marca": "boing",
    "pesoVolumen": 354.0,
    "unidadMedida": "PZS",
    "precioCompra": 16.25,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-09-30"
  },
  {
    "nombre": "boing de mango 354ml",
    "precio": 19.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "boing",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7501039400067",
    "proveedor": "BOING",
    "marca": "boing",
    "pesoVolumen": 354.0,
    "unidadMedida": "PZS",
    "precioCompra": 16.25,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-10-04"
  },
  {
    "nombre": "boing de uva 354ml",
    "precio": 19.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "boing",
    "stock": 5.0,
    "destacado": false,
    "codigoBarras": "7501039400098",
    "proveedor": "BOING",
    "marca": "boing",
    "pesoVolumen": 354.0,
    "unidadMedida": "PZS",
    "precioCompra": 16.25,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-10-06"
  },
  {
    "nombre": "boing de fresa 354ml",
    "precio": 19.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "boing",
    "stock": 4.0,
    "destacado": false,
    "codigoBarras": "7501039400074",
    "proveedor": "BOING",
    "marca": "boing",
    "pesoVolumen": 354.0,
    "unidadMedida": "PZS",
    "precioCompra": 16.25,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-10-08"
  },
  {
    "nombre": "POWER ADE 1L MELON",
    "precio": 34.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MELON",
    "stock": 6.0,
    "destacado": false,
    "codigoBarras": "7501055391400",
    "proveedor": "COCA COLA",
    "marca": "POWER ADE",
    "pesoVolumen": 1.0,
    "unidadMedida": "ML",
    "precioCompra": 28.33,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-10-20"
  },
  {
    "nombre": "COCA COLA 1.35L",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "SIN AZUCAR",
    "stock": 5.0,
    "destacado": false,
    "codigoBarras": "7501055374755",
    "proveedor": "COCA COLA",
    "marca": "COCA COLA",
    "pesoVolumen": 1.35,
    "unidadMedida": "Pieza",
    "precioCompra": 17.50,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-05-26"
  },
  {
    "nombre": "CHIPS 52g CREMA Y ESPECIAS",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CREMA Y ESPECIAS",
    "stock": 4.0,
    "destacado": false,
    "codigoBarras": "7500810039168",
    "proveedor": "BARCEL",
    "marca": "BARCEL",
    "pesoVolumen": 52.0,
    "unidadMedida": "PZS",
    "precioCompra": 15.56,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-08-24"
  },
  {
    "nombre": "NOPALES VERDURA",
    "precio": 30.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "NOPALES",
    "stock": 3.333,
    "destacado": false,
    "codigoBarras": "55",
    "proveedor": "GENERICO",
    "marca": "GENERICA",
    "pesoVolumen": 1.0,
    "unidadMedida": "KG",
    "precioCompra": 25.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-04-25"
  },
  {
    "nombre": "RED COLA 237ml LATA",
    "precio": 10.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "LATA",
    "stock": 13.0,
    "destacado": false,
    "codigoBarras": "606110023887",
    "proveedor": "RED COLA",
    "marca": "RED COLA",
    "pesoVolumen": 237.0,
    "unidadMedida": "PZS",
    "precioCompra": 8.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-09-27"
  },
  {
    "nombre": "TUBI 185g SURTIDO",
    "precio": 23.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CACAHUATE SOL",
    "stock": 1.0,
    "destacado": false,
    "codigoBarras": "7503007176387",
    "proveedor": "LA BOTANITA",
    "marca": "SOL",
    "pesoVolumen": 185.0,
    "unidadMedida": "Pieza",
    "precioCompra": 18.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-06-22"
  },
  {
    "nombre": "TUBI 100g RUSA",
    "precio": 23.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "PEPITA DE CALABAZA",
    "stock": 4.0,
    "destacado": false,
    "codigoBarras": "7503022458215",
    "proveedor": "LA BOTANITA",
    "marca": "SOL",
    "pesoVolumen": 100.0,
    "unidadMedida": "Pieza",
    "precioCompra": 18.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-08-21"
  },
  {
    "nombre": "SKWINKLES 45g",
    "precio": 20.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CHUNKS SABOR SANDIA",
    "stock": 12.0,
    "destacado": false,
    "codigoBarras": "7502271917696",
    "proveedor": "ZORRO",
    "marca": "SKWINKLES",
    "pesoVolumen": 45.0,
    "unidadMedida": "Pieza",
    "precioCompra": 15.53,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-07-19"
  },
  {
    "nombre": "TRAMPA CATCH-A MAX",
    "precio": 66.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "TRAMPA PARA RATONES",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7503013328015",
    "proveedor": "ZORRO",
    "marca": "CATCHA_MAX",
    "pesoVolumen": 1.0,
    "unidadMedida": "PZS",
    "precioCompra": 51.29,
    "puntoReorden": 1,
    "fechaVencimiento": "2099-09-09"
  },
  {
    "nombre": "MAZAPAN 50g",
    "precio": 8.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "GIGANTE",
    "stock": 35.0,
    "destacado": false,
    "codigoBarras": "724869001397",
    "proveedor": "ZORRO",
    "marca": "DE LA ROSA",
    "pesoVolumen": 50.0,
    "unidadMedida": "PZS",
    "precioCompra": 5.05,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-12-12"
  },
  {
    "nombre": "ALIMENTO",
    "precio": 15.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "ALIMENTO PARA POLLO",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "9090",
    "proveedor": "ZORRO",
    "marca": "GENERICA",
    "pesoVolumen": 1.0,
    "unidadMedida": "KG",
    "precioCompra": 11.20,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-12-12"
  },
  {
    "nombre": "NATURELLA SUELTA",
    "precio": 4.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "INDIVIDUAL",
    "stock": 32.0,
    "destacado": false,
    "codigoBarras": "7500435138680",
    "proveedor": "ZORRO",
    "marca": "NATURELLA",
    "pesoVolumen": 1.0,
    "unidadMedida": "PZS",
    "precioCompra": 2.02,
    "puntoReorden": 1,
    "fechaVencimiento": "2028-04-04"
  },
  {
    "nombre": "MALVAVISCOS 400g BOMBON",
    "precio": 50.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "BOLSA COMPLETA",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "724869003315",
    "proveedor": "ZORRO",
    "marca": "BIANCHI",
    "pesoVolumen": 400.0,
    "unidadMedida": "PZS",
    "precioCompra": 32.05,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-04-04"
  },
  {
    "nombre": "MALVAVISCO",
    "precio": 3.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "INDIV PEQUEÑO",
    "stock": 45.0,
    "destacado": false,
    "codigoBarras": "724869003315",
    "proveedor": "ZORRO",
    "marca": "BIANCHI",
    "pesoVolumen": 400.0,
    "unidadMedida": "PZS",
    "precioCompra": 0.71,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-04-04"
  },
  {
    "nombre": "MAIZ QUEBRADO",
    "precio": 16.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MAIZ QUEBARDO",
    "stock": 10.0,
    "destacado": false,
    "codigoBarras": "7474",
    "proveedor": "ZORRO",
    "marca": "GENERICA",
    "pesoVolumen": 1.0,
    "unidadMedida": "KG",
    "precioCompra": 11.80,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-12-12"
  },
  {
    "nombre": "PALMOLIVE 120g",
    "precio": 26.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "MENTA Y EUCALIPTO",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7509546682266",
    "proveedor": "ZORRO",
    "marca": "PALMOLIVE",
    "pesoVolumen": 120.0,
    "unidadMedida": "PZS",
    "precioCompra": 17.78,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-09-09"
  },
  {
    "nombre": "PALMOLIVE 120g",
    "precio": 26.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "OLIVA Y ALO VERA",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7509546682471",
    "proveedor": "ZORRO",
    "marca": "PALMOLIVE",
    "pesoVolumen": 120.0,
    "unidadMedida": "PZS",
    "precioCompra": 17.78,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-12-12"
  },
  {
    "nombre": "ZEST 135g MAN",
    "precio": 23.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "JABON DE TOCADOR",
    "stock": 10.0,
    "destacado": false,
    "codigoBarras": "7506306246096",
    "proveedor": "ZORRO",
    "marca": "ZEST",
    "pesoVolumen": 135.0,
    "unidadMedida": "pzs",
    "precioCompra": 15.97,
    "puntoReorden": 1,
    "fechaVencimiento": "2029-02-02"
  },
  {
    "nombre": "PALMOLIVE 120g",
    "precio": 26.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "LAVANDA Y CREMA",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7509546682280",
    "proveedor": "ZORRO",
    "marca": "PALMOLIVE",
    "pesoVolumen": 120.0,
    "unidadMedida": "PZS",
    "precioCompra": 17.78,
    "puntoReorden": 1,
    "fechaVencimiento": "2028-03-03"
  },
  {
    "nombre": "PALMOLIVE 120g",
    "precio": 26.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "YOGHURT Y FRUTAS",
    "stock": 3.0,
    "destacado": false,
    "codigoBarras": "7509546682334",
    "proveedor": "ZORRO",
    "marca": "PALMOLIVE",
    "pesoVolumen": 120.0,
    "unidadMedida": "PZS",
    "precioCompra": 17.78,
    "puntoReorden": 1,
    "fechaVencimiento": "2028-01-01"
  },
  {
    "nombre": "SABA",
    "precio": 30.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "INVISIBLE",
    "stock": 2.0,
    "destacado": false,
    "codigoBarras": "7501019006371",
    "proveedor": "ZORRO",
    "marca": "SABA",
    "pesoVolumen": 10.0,
    "unidadMedida": "PZS",
    "precioCompra": 0.00,
    "puntoReorden": 1,
    "fechaVencimiento": "2029-03-03"
  },
  {
    "nombre": "PALETA TIX",
    "precio": 5.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "PALETA",
    "stock": 26.0,
    "destacado": false,
    "codigoBarras": "7171",
    "proveedor": "SABRITAS",
    "marca": "SONRICS",
    "pesoVolumen": 1.0,
    "unidadMedida": "PZS",
    "precioCompra": 4.05,
    "puntoReorden": 1,
    "fechaVencimiento": "2026-12-12"
  },
  {
    "nombre": "CONEJOS 20g TURIN",
    "precio": 13.00,
    "categoria": "abarrotes",
    "imagen": null,
    "descripcion": "CHOCOLATE",
    "stock": 16.0,
    "destacado": false,
    "codigoBarras": "756774060527",
    "proveedor": "COCA COLA",
    "marca": "TURIN",
    "pesoVolumen": 20.0,
    "unidadMedida": "Pieza",
    "precioCompra": 9.20,
    "puntoReorden": 1,
    "fechaVencimiento": "2027-09-13"
  }
]

async function subirProductos() {
  try {
    console.log("🚀 Iniciando subida de productos...");
    
    for (const producto of productos) {
      const docRef = await db.collection("productos").add(producto);
      console.log(`✅ Producto "${producto.nombre}" agregado con ID: ${docRef.id}`);
    }
    
    console.log("🎉 ¡Todos los productos se subieron correctamente!");
  } catch (error) {
    console.error("❌ Error al subir productos: ", error);
  }
}

// Ejecutar la función
subirProductos();